### ISSUE TITLE
Extra query parameters are accepted in query

### ISSUE THREAD

**Issue by tomisargiottob** [seriousme/fastify-openapi-glue#288]
Hello, i am trying to use openapi-glue in a project but i have faced a problem that i would like to know if it should work like this. I have a DELETE endpoint where i can send the ids of the agents i want to delete as query parameters. For example:
 `/groups/16705c05-3f5c-4e02-95a2-6f3f551c620b/agents?where[id][inq]=278...`. 
 Here i have the specification for the following endpoint:

```
  delete:
    summary: Remove multiple agents from group
    description: Remove multiple agents from selection group.
    operationId: removeMultipleAgentsFromGroup
    tags:
      - Agents
    parameters:
      - name: id
        description: Group ID
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: where
        in: query
        description: Items to filter
        # style: deepObject
        explode: false
        schema:
          type: object
          additionalProperties: false
          properties:
            id:
              type: object
              additionalProperties: false
              properties:
                inq:
                  type: array
                  items:
                    type: string
    responses:
      200:
        description: Agents part of a group.
        content:
          application/json:
            schema:
              type: object
              properties:
                agents:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      priority:
                        type: integer
                count:
                  type: integer
      401:
        $ref: 'errors.yaml#/components/responses/Unauthorized'
      404:
        $ref: 'errors.yaml#/components/responses/NotFound'
      500:
        $ref: 'errors.yaml#/components/responses/InternalServer'
```
The problems that i am having are two, on the one hand, i had to add **explode false** to avoid the parser to parse only the schema of the query parameter (function parseQueryString in openapi-glue). if i don't add it, i don't recieve any information past the openapi validation . The thing is that i want to add style: deepObject which it says that by default sets explode to true, so it is contradictory. (documentation of openapi about style: https://spec.openapis.org/oas/v3.1.0#style-examples )Is this supposed to work like this?  

On the other hand, i would like openapi to stop all the queries that have extra query parameters apart from **where**. For example, if i send the following request `/groups/16705c05-3f5c-4e02-95a2-6f3f551c620b/agents?blabla[id][inq]=278`, openapi does not stop this as a bad request. Is there any way to add a additionalProperties: false to the query?

The configuration that i have set for ajv is `coerceTypes: 'array'` and i have also tried with `removeAdditional: false,` but did not get expected result.

Thank you for your time

**Comment by seriousme** [comment]
Hi,

thanks for asking.

Although REST is not formally standardized, the whole concept of REST is based  on resource identifiers (not on SQL ;-))
(see: https://blog.stoplight.io/rest-api-standards-do-they-even-exist)

The idea being that you Delete a specific resource (`Delete /animals/cat`) and *not* by providing a query 
( `Delete /animals?where[legs]=4`) Queries should only be passed to Get operations ;-)

According to the openAPI spec the style/explode properties are specific to RFC6570. To my knowledge Fastify does not support RFC6570 so fastify-openapi-glue can not generate configuration data for this. 

More information on querystring schema in Fastify can be found at: https://www.mikulskibartosz.name/query-string-validation-in-fastify/

What you could try is [generating code](https://github.com/seriousme/fastify-openapi-glue#generator) from your specification and see how your spec is interpreted. 

Hope this helps.

Kind regards,
Hans

**Comment by seriousme** [comment]
Hi,

Small addition: you can provide your own query string parser to fastify.
https://www.fastify.io/docs/latest/Server/#querystringparser
Once querystring parsing goes as planned then AJV should have no issues with your schema anymore.

Kind regards,
Hans

**Comment by tomisargiottob** [comment]
Hi, thanks for the quick reply.

I understand what you are saying but actually there are a couple more things to consider to understand what i am trying to do.

- I am using the loopback query format.
- I have provided my own query string parser with qs.
- I am using query parameters in a Delete endpoint becouse i am trying to create an endpoint for batch delete. So i need the query parameters to identify the resources to delete for example `agents?where[id][inq]=278&agents?where[id][inq]=276` . This is why i am forced to use query parameters to send all the resources indicated. Anyways, apart from the reason of why i am using this format, this behaviour would reproduce in a get endpoint.

The following code is an example of the problem i am facing, given the following openapi spec:
```
"delete": {
        "summary": "Remove multiple agents from group",
        "description": "Remove multiple agents from selection group.",
        "operationId": "removeMultipleAgentsFromGroup",
        "tags": [
          "Agents"
        ],
        "parameters": [
          {
            "name": "id",
            "description": "Group ID",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "where",
            "in": "query",
            "description": "Items to filter",
            "explode": false,
            "schema": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "inq": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
```
This specification gets translated with open api glue to the following:
```
Operation: removeMultipleAgentsFromGroup
URL: /groups/:id/agents
summary:  Remove multiple agents from group
req.params
    type: object
    properties:
    id:
        type: string
        format: uuid
        description: Group ID
    required:
    - id

req.query
    type: object
    properties:
    where:
        type: object
        additionalProperties: false
        properties:
        id:
            type: object
            additionalProperties: false
            properties:
            inq:
                type: array
                items:
                type: string
        description: Items to filter
```
But if i remove the explode parameter from the where parameter and add style: "deepObject" , as it is shown below:
```
"delete": {
        "summary": "Remove multiple agents from group",
        "description": "Remove multiple agents from selection group.",
        "operationId": "removeMultipleAgentsFromGroup",
        "tags": [
          "Agents"
        ],
        "parameters": [
          {
            "name": "id",
            "description": "Group ID",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "where",
            "in": "query",
            "description": "Items to filter",
            "style": "deepObject",
            "schema": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "inq": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
```
When i use this specification with open-api-glue, it is translated to the following:
```
 Operation: removeMultipleAgentsFromGroup
 URL: /groups/:id/agents
 summary:  Remove multiple agents from group
 req.params
   type: object
   properties:
     id:
       type: string
       format: uuid
       description: Group ID
   required:
     - id

 req.query
   type: object
   additionalProperties: false
   properties:
     id:
       type: object
       additionalProperties: false
       properties:
         inq:
           type: array
           items:
             type: string
```
As you can see, the second translation is avoiding the where clause in the req.query which is giving problems at the time of validation. This is the unexpected behaviour i am facing. This problem does not occur if there is more than one query parameter.
