### ISSUE TITLE
No validation error when non `application/json` response provided by API

### ISSUE THREAD

**Issue by alebas1** [seriousme/fastify-openapi-glue#475]
Hello, I just started using this project in my fastify API.

I noticed that no validation errors were returned when my API returned a non `application/json` response (tested only with `text/plain` and an emptyresponse body)

For example, I have my OpenAPI document with this schema:
```yaml
components:
  schemas:
    Health:
      type: object
      properties:
        status:
          type: string
          example: OK
          enum:
            - OK
            - KO
      required:
        - status
```

And if the route returns a text/plain response, for example:
```js
const options: FastifyOpenapiGlueOptions = {
  specification: path.join(dirName, '../docs/openapi-spec.yaml'),
  service: {
    "health": async () => "FOO", // <--- here
  }
}
```
When I `curl -v localhost:8080/health`, no validation error is returned and the "FOO" string is successfully returned.

I guess that the expected response would be a 500 with a body like that:
```
{"statusCode":500,"error":"Internal Server Error","message":"\"status\" is required!"}
```

Is it a bug or a feature? 😄 

Thanks !
