### ISSUE TITLE
Multiple Security Handlers Error Handling

### ISSUE THREAD

**Issue by AlexBroadbent** [seriousme/fastify-openapi-glue#557]
I'm having some trouble with excessive logging when I have a resource which has two security options. The expected case of if one passes then the request is allowed, but I have logging in both security handlers that will log an error. Because one security handler can't tell if the other one will/has pass, it's assumed to be a fail and so the error is logged.

A simplistic use case:

```
paths:
  "/resource":
    get:
      summary: Get Resource
      operationId: getResource
      security:
        - api_key:
            - resource:read
        - api_token:
            - resource:read
```

In this case, my `api_key` and `api_token` functions will be called and they are both a very simple implementation of:

```javascript
export const api_key = (request, reply, params) => if (!isRequestValid(request, params)) throw new Error("Invalid request");
export const api_token = (request, reply, params) => if (!isRequestValid(request, params)) throw new Error("Invalid request");
```

Authenticating the request with a valid API key will throw an error from the `api_token` handler and having a vice versa with a valid API token.

---

Is there any way that you could pass through additional context into the security handlers to handle this, ie. if there are more than one handlers validating the request, only the last handler to be run would throw an error and the rest would just log that they don't match silently. @seriousme
